
name: Linux build

on:
  push:
    branches:
    - '**'

env:
  LANG: en_US.UTF-8
  JVMCI_VERSION: jvmci-22.0-b03

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Libraries
      run: |
          sudo apt update
          sudo apt install libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev libcups2-dev
    
    - name: Configure
      run: |
        sh configure --with-conf-name=labsjdk --with-version-opt=${{ env.JVMCI_VERSION }} --with-version-pre= '--with-vendor-name=GraalVM Community' --with-vendor-url=https://www.graalvm.org/ --with-vendor-bug-url=https://github.com/oracle/graal/issues --with-vendor-vm-bug-url=https://github.com/oracle/graal/issues
        make CONF_NAME=labsjdk graal-builder-image
        zip -rq labsjdk-17-linux.zip build/labsjdk/images/graal-builder-jdk
        
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: labsjdk-17-linux
        path: labsjdk-17-linux.zip
